version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: petsitters_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: petsitters
      POSTGRES_PASSWORD: petsitters
      POSTGRES_DB: petsitters_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
